#!/bin/bash

docker rm dockiera-agent-container
docker rmi dockiera-agent-image

docker build -t dockiera-agent-image .
docker run --name dockiera-agent-container --network=dockiera-app_default -v /var/run/docker.sock:/var/run/docker.sock --env-file .env dockiera-agent-image
