#INFLUX
INFLUXDB_ORGANIZATION = "agh-utc"
INFLUXDB_URL = "http://localhost:8086"
INFLUXDB_BUCKET = "dockeria"
INFLUXDB_TOKEN = "yourtokenhere"
INFLUXDB_WRITE_INTERVAL_TIME = 10

#DEV
HOME_PATH = '/'
MAX_WORKERS = 50